name: '[Reusable] Build'

on:
  workflow_call:
    inputs:
      configuration:
        type: string
      solution:
        type: string
      filename:
        type: string

jobs:
  reusable_workflow_job:
    runs-on:  windows-latest
    env:
      Solution_Name: Holos.sln
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0        

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # TODO: remove unit tests for now, to speed up testing
    # - name: Setup VSTest
    #   uses: darenm/Setup-VSTest@v1

    - name: Restore nuget packages
      run: msbuild ${{ inputs.solution }} /t:Restore /m
      env:
        Configuration: ${{ inputs.configuration }}

    - name: Build solution
      run: msbuild ${{ inputs.solution }} /p:platform="Any CPU" /p:Configuration=$env:Configuration /m
      env:
        Configuration: ${{ inputs.configuration }}

    - name: Run Tests
      run: vstest.console.exe ./**/H.Core.Test/bin/${{ inputs.configuration }}/H.Core.Test.dll ./**/H.Infrastructure.Test/bin/${{ inputs.configuration }}/H.Infrastructure.Test.dll ./**/H.CLI.Test/bin/${{ inputs.configuration }}/H.CLI.Test.dll /Parallel

    - name: Upload build artifacts
      if: ${{ inputs.configuration == 'Release' }}
      uses: actions/upload-artifact@v4
      with:
        name: Holos4-lib
        path: '**/H.Core/bin/*'